sys:
  debug:
    #DEBUG开关
    switch:
      true
    #ignoreLogin 是否忽略注释 true、false
    ignoreLogin:
      false
  cache:
    mapperbeans:
      dmGbMapper,dmXbMapper,dmCfmdMapper,dmCgspjgMapper,dmHzztMapper,dmJflyMapper,dmJhlxMapper,dmLfmdMapper,dmTzjbMapper,dmTzlbMapper,dmWblfJdlxMapper,dmXmccMapper,dmXmlxMapper,dmXmmcMapper,dmZzskMapper
  access:
    #忽略访问，ext为忽略扩展名，url，为忽略路径
    ignore:
      ext:
        css,js,png,gif,jpg,woff,woff2,otf,svg,ttf,eot
      url:
  upload:
    #上传文件的基本路径
    base_dir:
      D:\\upload\\

